from setuptools import setup, find_packages
import pathlib

here = pathlib.Path(__file__).parent.resolve()

# Get the long description from the README file
long_description = (here / "README.md").read_text(encoding="utf-8")

setup(
    name="vehicle-telemetry-analytics",
    version="1.0.0",
    description="Advanced Vehicle Telemetry Analytics Platform",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/vehicle-telemetry-analytics",
    author="Your Name",
    author_email="your.email@example.com",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
    keywords="vehicle, telemetry, analytics, iot, data-science, machine-learning",
    package_dir={"": "src"},
    packages=find_packages(where="src"),
    python_requires=">=3.8, <4",
    install_requires=[
        "pandas>=1.5.0",
        "numpy>=1.23.0",
        "scikit-learn>=1.2.0",
        "matplotlib>=3.6.0",
        "seaborn>=0.12.0",
        "plotly>=5.13.0",
        "sqlalchemy>=2.0.0",
        "pyspark>=3.4.0",
        "kafka-python>=2.0.2",
        "pyyaml>=6.0",
        "scipy>=1.10.0",
        "streamlit>=1.23.0",
        "dash>=2.11.0",
        "flask>=2.3.0",
        "psycopg2-binary>=2.9.6",
        "pytest>=7.3.0",
        "pytest-cov>=4.0.0",
        "prefect>=2.10.0",
        "mlflow>=2.4.0",
        "xgboost>=1.7.0",
        "catboost>=1.2.0",
        "lightgbm>=4.0.0",
        "prophet>=1.1.0",
        "tensorflow>=2.12.0",
        "torch>=2.0.0",
        "transformers>=4.30.0",
        "sentence-transformers>=2.2.0",
        "openpyxl>=3.1.0",
        "polars>=0.18.0",
        "pyarrow>=12.0.0",
        "fastapi>=0.100.0",
        "uvicorn>=0.23.0",
        "redis>=5.0.0",
        "celery>=5.3.0",
        "dask>=2023.6.0",
        "ray>=2.5.0",
        "prometheus-client>=0.17.0",
        "grafana-api>=1.0.3",
        "docker>=6.1.0",
        "kubernetes>=26.1.0",
        "boto3>=1.28.0",
        "azure-storage-blob>=12.17.0",
        "google-cloud-storage>=2.10.0",
    ],
    extras_require={
        "dev": [
            "pytest",
            "pytest-cov",
            "black",
            "flake8",
            "mypy",
            "isort",
            "jupyter",
            "jupyterlab",
            "notebook",
            "ipython",
        ],
        "docs": [
            "sphinx",
            "sphinx-rtd-theme",
            "nbsphinx",
            "sphinx-autodoc-typehints",
        ],
        "streaming": [
            "kafka-python",
            "confluent-kafka",
            "pyspark[sql,streaming]",
            "apache-flink",
            "apache-beam",
        ],
    },
    entry_points={
        "console_scripts": [
            "vehicle-analytics=main:main",
            "vehicle-streaming=streaming.kafka.producer:main",
            "vehicle-spark=streaming.spark.streaming_processor:main",
        ],
    },
    project_urls={
        "Bug Reports": "https://github.com/yourusername/vehicle-telemetry-analytics/issues",
        "Source": "https://github.com/yourusername/vehicle-telemetry-analytics",
        "Documentation": "https://yourusername.github.io/vehicle-telemetry-analytics/",
    },
)